export const intranetRoutesData = [
  {
    id: "facturacion",
    name: "Facturación",
    path: "/panel-administracion/comprobantes",
    isLink: false,
    checked: false,
    icon: "BookOpen",
    hasParents: false,
    children: [
      {
        id: "comp-venta",
        name: "Comp. de venta",
        path: "/panel-administracion/comprobantes/comprobantes-de-venta",
        isLink: false,
        checked: false,
        icon: "BookOpen",
        hasParents: true,
        children: [
          {
            id: "emitir",
            name: "Emitir",
            path: "/panel-administracion/comprobantes/comprobantes-de-venta/emitir",
            isLink: true,
            checked: false,
            icon: "Send",
            hasParents: true,
            children: [],
          },
          {
            id: "listado",
            name: "Listado",
            path: "/panel-administracion/comprobantes/comprobantes-de-venta/voucher-list",
            isLink: true,
            checked: false,
            icon: "FileStack",
            hasParents: true,
            children: [],
          },
        ],
      },
      {
        id: "comp-recepcion",
        name: "Comp. de recepción",
        path: "/panel-administracion/comprobantes/comprobantes-de-recepcion",
        isLink: false,
        checked: false,
        icon: "BookOpen",
        hasParents: true,
        children: [],
      },
    ],
  },
  {
    id: "almacen",
    name: "Almacén",
    path: "/panel-administracion/almacen",
    isLink: false,
    checked: false,
    icon: "Package2",
    hasParents: false,
    children: [
      {
        id: "ubicaciones",
        name: "Ubicaciones",
        path: "/panel-administracion/almacen/ubicaciones",
        isLink: true,
        checked: false,
        icon: "MapPinned",
        hasParents: true,
        children: [],
      },
    ],
  },
  {
    id: "accesos",
    name: "Accesos",
    path: "/panel-administracion/accesos",
    isLink: false,
    checked: false,
    icon: "Shield",
    hasParents: false,
    children: [
      {
        id: "usuarios",
        name: "Usuarios",
        path: "/panel-administracion/accesos/usuarios",
        isLink: true,
        checked: false,
        icon: "User",
        hasParents: true,
        children: [],
      },
    ],
  },
];
